spring:
  jackson:
    default-property-inclusion: non_empty
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}"
    url: "jdbc:mysql://${DB_HOST:110.42.204.86}:${DB_PORT:3306}/low_code?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia%2FShanghai"
    username: "${DB_NAME:notebook}"
    password: "${DB_PWD:123@Telenor}"
    hikari:
      maximumPoolSize: "${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:16}"
  redis:
    # 地址
    host: 110.42.204.86
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 2
    # 密码
    password: 123@Telenor
    # 连接超时时间
    timeout: 30s
  main:
    banner-mode: off
  messages:
    basename: i18n/messages
    encoding: utf-8


mybatis-plus:
  type-aliases-package: com.jeanne.lowcode.entity
  type-enums-package: com.jeanne.lowcode.entity.enums
  mapper-locations: classpath:sqlmap/*.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
      column-underline: true
    mapper-registry-cache:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#    cache-enabled: true
logging:
  level:
    root: info
server:
  port: 33001
  tomcat:
    accept-count: 50
  shutdown: graceful
  servlet:
    context-path: /lowcode

